-- TO-BE schema module: master / stage: test
-- ==========================================================================
--  Project: master (顧客・商品マスタ)
--  Source: db/asis/01_master_oracle.sql
--  他モジュールが参照するマスタ。スキーマ作成もここで実施。
-- ==========================================================================

CREATE SCHEMA IF NOT EXISTS securities;
SET search_path = securities, public;

-- --------------------------------------------------------------------------
--  顧客マスタ
-- --------------------------------------------------------------------------
CREATE TABLE securities.customer (
    customer_id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code        VARCHAR(20)   NOT NULL UNIQUE,
    customer_name        VARCHAR(100)  NOT NULL,
    customer_name_kana   VARCHAR(200),
    birth_date           DATE,
    gender               CHAR(1)       CHECK (gender IN ('M', 'F')),
    email                VARCHAR(128),
    phone                VARCHAR(20),
    created_at           TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP
);

CREATE INDEX ix_customer_email_lower ON securities.customer (LOWER(email));

COMMENT ON TABLE  securities.customer                    IS '顧客マスタ';
COMMENT ON COLUMN securities.customer.customer_code      IS '顧客コード';
COMMENT ON COLUMN securities.customer.customer_name      IS '顧客名';
COMMENT ON COLUMN securities.customer.customer_name_kana IS '顧客名カナ';
COMMENT ON COLUMN securities.customer.gender             IS '性別区分 M=男 / F=女';

-- --------------------------------------------------------------------------
--  商品マスタ
-- --------------------------------------------------------------------------
CREATE TABLE securities.product (
    product_id           INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code         VARCHAR(20)   NOT NULL UNIQUE,
    product_name         VARCHAR(100)  NOT NULL,
    product_kind         CHAR(2)       NOT NULL CHECK (product_kind IN ('10', '20', '30')),
    unit_price           NUMERIC(15,4),
    currency_code        CHAR(3)       NOT NULL DEFAULT 'JPY',
    created_at           TIMESTAMP     NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  securities.product               IS '商品マスタ';
COMMENT ON COLUMN securities.product.product_kind  IS '商品種別 10=株式 / 20=債券 / 30=投資信託';
COMMENT ON COLUMN securities.product.unit_price    IS '単価';
COMMENT ON COLUMN securities.product.currency_code IS '通貨コード ISO 4217';
