-- TO-BE schema module: account / stage: test
-- ==========================================================================
--  Project: account (口座・保有関係)
--  依存: 01_master (customer, product), 02_organization (branch)
-- ==========================================================================

SET search_path = securities, public;

-- --------------------------------------------------------------------------
--  口座マスタ (customer 1:N)
-- --------------------------------------------------------------------------
CREATE TABLE securities.account (
    account_id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id          BIGINT        NOT NULL,
    branch_id            INTEGER       NOT NULL,
    account_no           VARCHAR(20)   NOT NULL UNIQUE,
    account_kind         CHAR(2)       NOT NULL CHECK (account_kind IN ('01', '02')),
    balance              NUMERIC(15,2) NOT NULL DEFAULT 0,
    opened_date          DATE          NOT NULL,
    status               CHAR(1)       NOT NULL CHECK (status IN ('A', 'C', 'F')),
    created_at           TIMESTAMP     NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP,
    CONSTRAINT fk_account_customer
      FOREIGN KEY (customer_id) REFERENCES securities.customer (customer_id),
    CONSTRAINT fk_account_branch
      FOREIGN KEY (branch_id)   REFERENCES securities.branch (branch_id)
);

COMMENT ON TABLE  securities.account              IS '口座マスタ';
COMMENT ON COLUMN securities.account.account_kind IS '口座種別 01=普通 / 02=特定';
COMMENT ON COLUMN securities.account.status       IS '状態 A=有効 / C=停止 / F=閉鎖';
COMMENT ON COLUMN securities.account.balance      IS '残高';

-- --------------------------------------------------------------------------
--  口座-商品 保有関係 (N:N, composite PK)
-- --------------------------------------------------------------------------
CREATE TABLE securities.account_product (
    account_id           BIGINT        NOT NULL,
    product_id           INTEGER       NOT NULL,
    holding_qty          NUMERIC(15,4) NOT NULL DEFAULT 0,
    start_date           DATE          NOT NULL,
    end_date             DATE,
    created_at           TIMESTAMP     NOT NULL DEFAULT NOW(),
    PRIMARY KEY (account_id, product_id),
    CONSTRAINT fk_account_product_account
      FOREIGN KEY (account_id) REFERENCES securities.account (account_id),
    CONSTRAINT fk_account_product_product
      FOREIGN KEY (product_id) REFERENCES securities.product (product_id)
);

COMMENT ON TABLE  securities.account_product             IS '口座-商品 保有関係 (N:N)';
COMMENT ON COLUMN securities.account_product.holding_qty IS '保有数量';
