-- TO-BE schema for stage: test
-- ==========================================================================
--  日本の証券会社の口座/取引系 (PostgreSQL 18 target).
--  Source: db/asis/oracle_ddl.sql. 4 stages share an identical schema —
--  only the header line above differs.
--
--  Oracle → PostgreSQL conversion applied:
--    VARCHAR2(n)            → VARCHAR(n)
--    NUMBER(p,s) (s > 0)    → NUMERIC(p,s)
--    NUMBER(p)   (integer)  → INTEGER / BIGINT / SMALLINT by precision
--    DATE                   → TIMESTAMP
--    SYSDATE                → NOW()
--    sequence + nextval     → GENERATED BY DEFAULT AS IDENTITY
--    ROWNUM / hints         → dropped
--
--  Naming: snake_case (customer / account / product / trade / account_product).
--  FKs declared at end of file via ALTER TABLE so creation order is
--  irrelevant and the file is easy to diff.
-- ==========================================================================

-- --------------------------------------------------------------------------
--  顧客マスタ
-- --------------------------------------------------------------------------
CREATE TABLE customer (
    customer_id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code        VARCHAR(20)  NOT NULL UNIQUE,
    customer_name        VARCHAR(100) NOT NULL,
    customer_name_kana   VARCHAR(200),
    birth_date           DATE,
    gender               CHAR(1)      CHECK (gender IN ('M', 'F')),
    email                VARCHAR(128),
    phone                VARCHAR(20),
    created_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP
);

COMMENT ON TABLE  customer                    IS '顧客マスタ';
COMMENT ON COLUMN customer.customer_code      IS '顧客コード';
COMMENT ON COLUMN customer.customer_name      IS '顧客名';
COMMENT ON COLUMN customer.customer_name_kana IS '顧客名カナ';
COMMENT ON COLUMN customer.gender             IS '性別区分 M=男 / F=女';

-- --------------------------------------------------------------------------
--  商品マスタ
-- --------------------------------------------------------------------------
CREATE TABLE product (
    product_id           INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code         VARCHAR(20)  NOT NULL UNIQUE,
    product_name         VARCHAR(100) NOT NULL,
    product_kind         CHAR(2)      NOT NULL CHECK (product_kind IN ('10', '20', '30')),
    unit_price           NUMERIC(15,4),
    currency_code        CHAR(3)      NOT NULL DEFAULT 'JPY',
    created_at           TIMESTAMP    NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  product               IS '商品マスタ';
COMMENT ON COLUMN product.product_kind  IS '商品種別 10=株式 / 20=債券 / 30=投資信託';
COMMENT ON COLUMN product.unit_price    IS '単価';
COMMENT ON COLUMN product.currency_code IS '通貨コード ISO 4217';

-- --------------------------------------------------------------------------
--  口座マスタ (customer 1:N)
-- --------------------------------------------------------------------------
CREATE TABLE account (
    account_id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id          BIGINT       NOT NULL,
    account_no           VARCHAR(20)  NOT NULL UNIQUE,
    account_kind         CHAR(2)      NOT NULL CHECK (account_kind IN ('01', '02')),
    balance              NUMERIC(15,2) NOT NULL DEFAULT 0,
    opened_date          DATE         NOT NULL,
    status               CHAR(1)      NOT NULL CHECK (status IN ('A', 'C', 'F')),
    created_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMP
);

COMMENT ON TABLE  account              IS '口座マスタ';
COMMENT ON COLUMN account.account_kind IS '口座種別 01=普通 / 02=特定';
COMMENT ON COLUMN account.status       IS '状態 A=有効 / C=停止 / F=閉鎖';
COMMENT ON COLUMN account.balance      IS '残高';

-- --------------------------------------------------------------------------
--  口座-商品 保有関係 (N:N, composite PK)
-- --------------------------------------------------------------------------
CREATE TABLE account_product (
    account_id           BIGINT        NOT NULL,
    product_id           INTEGER       NOT NULL,
    holding_qty          NUMERIC(15,4) NOT NULL DEFAULT 0,
    start_date           DATE          NOT NULL,
    end_date             DATE,
    created_at           TIMESTAMP     NOT NULL DEFAULT NOW(),
    PRIMARY KEY (account_id, product_id)
);

COMMENT ON TABLE  account_product             IS '口座-商品 保有関係 (N:N)';
COMMENT ON COLUMN account_product.holding_qty IS '保有数量';

-- --------------------------------------------------------------------------
--  取引明細 (N:1 → account, N:1 → product)
-- --------------------------------------------------------------------------
CREATE TABLE trade (
    trade_id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id           BIGINT        NOT NULL,
    product_id           INTEGER       NOT NULL,
    trade_type           CHAR(1)       NOT NULL CHECK (trade_type IN ('B', 'S')),
    trade_qty            NUMERIC(12)   NOT NULL,
    trade_price          NUMERIC(15,4) NOT NULL,
    trade_date           DATE          NOT NULL,
    created_at           TIMESTAMP     NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_trade_account_date ON trade (account_id, trade_date);

COMMENT ON TABLE  trade             IS '取引明細';
COMMENT ON COLUMN trade.trade_type  IS '取引種別 B=買付 / S=売却';
COMMENT ON COLUMN trade.trade_qty   IS '取引数量';
COMMENT ON COLUMN trade.trade_price IS '約定単価';

-- --------------------------------------------------------------------------
--  Foreign keys (declared last so creation order is irrelevant)
-- --------------------------------------------------------------------------
ALTER TABLE account
    ADD CONSTRAINT fk_account_customer
    FOREIGN KEY (customer_id) REFERENCES customer (customer_id);

ALTER TABLE account_product
    ADD CONSTRAINT fk_account_product_account
    FOREIGN KEY (account_id) REFERENCES account (account_id),
    ADD CONSTRAINT fk_account_product_product
    FOREIGN KEY (product_id) REFERENCES product (product_id);

ALTER TABLE trade
    ADD CONSTRAINT fk_trade_account
    FOREIGN KEY (account_id) REFERENCES account (account_id),
    ADD CONSTRAINT fk_trade_product
    FOREIGN KEY (product_id) REFERENCES product (product_id);
