-- TO-BE schema module: organization / stage: staging
-- ==========================================================================
--  Project: organization (営業店・社員)
--  依存: なし (master と並行可能だが順序的に master の次)
-- ==========================================================================

SET search_path = securities, public;

-- --------------------------------------------------------------------------
--  営業店マスタ (self-referencing FK + TEXT + BOOLEAN + DEFAULT)
-- --------------------------------------------------------------------------
CREATE TABLE securities.branch (
    branch_id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_code          VARCHAR(10)   NOT NULL UNIQUE,
    branch_name          VARCHAR(80)   NOT NULL,
    parent_branch_id     INTEGER,
    address              TEXT,
    opened_date          DATE          NOT NULL,
    is_active            BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_branch_parent
      FOREIGN KEY (parent_branch_id) REFERENCES securities.branch (branch_id)
);

COMMENT ON TABLE  securities.branch                  IS '営業店マスタ';
COMMENT ON COLUMN securities.branch.parent_branch_id IS '上位営業店 ID. NULL は本部 / 統括拠点.';
COMMENT ON COLUMN securities.branch.is_active        IS '稼働フラグ';

-- --------------------------------------------------------------------------
--  社員マスタ (FK branch + self-ref manager + CHECK role + partial index)
-- --------------------------------------------------------------------------
CREATE TABLE securities.employee (
    employee_id          BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_code        VARCHAR(20)   NOT NULL UNIQUE,
    employee_name        VARCHAR(100)  NOT NULL,
    branch_id            INTEGER       NOT NULL,
    manager_id           BIGINT,
    role                 VARCHAR(10)   NOT NULL CHECK (role IN ('営業', '管理', '事務', '監査', 'IT')),
    email                VARCHAR(128)  NOT NULL UNIQUE,
    hired_date           DATE          NOT NULL,
    is_active            BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_employee_branch
      FOREIGN KEY (branch_id) REFERENCES securities.branch (branch_id),
    CONSTRAINT fk_employee_manager
      FOREIGN KEY (manager_id) REFERENCES securities.employee (employee_id)
);

CREATE INDEX ix_employee_active ON securities.employee (branch_id, role) WHERE is_active = TRUE;

COMMENT ON TABLE  securities.employee            IS '社員マスタ';
COMMENT ON COLUMN securities.employee.manager_id IS '上司の employee_id (自己参照, NULL 可).';
COMMENT ON COLUMN securities.employee.role       IS '職種コード 営業 / 管理 / 事務 / 監査 / IT';
