-- TO-BE schema module: market / stage: staging
-- ==========================================================================
--  Project: market (気配値スナップショット)
--  依存: 01_master (product)
-- ==========================================================================

SET search_path = securities, public;

-- TIMESTAMPTZ + JSONB + composite descending index
CREATE TABLE securities.market_quote (
    quote_id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id           INTEGER       NOT NULL,
    quote_ts             TIMESTAMPTZ   NOT NULL,
    payload              JSONB         NOT NULL,
    source               VARCHAR(20)   NOT NULL DEFAULT 'EXCHANGE',
    CONSTRAINT fk_market_quote_product
      FOREIGN KEY (product_id) REFERENCES securities.product (product_id)
);

CREATE INDEX ix_market_quote_product_ts ON securities.market_quote (product_id, quote_ts DESC);

COMMENT ON TABLE  securities.market_quote         IS '気配値スナップショット';
COMMENT ON COLUMN securities.market_quote.payload IS 'bid/ask/volume/spread 等の可変フィールド';
