-- TO-BE schema module: trade / stage: dev
-- ==========================================================================
--  Project: trade (取引明細)
--  依存: 01_master (product), 03_account (account)
-- ==========================================================================

SET search_path = securities, public;

CREATE TABLE securities.trade (
    trade_id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id           BIGINT        NOT NULL,
    product_id           INTEGER       NOT NULL,
    trade_type           CHAR(1)       NOT NULL CHECK (trade_type IN ('B', 'S')),
    trade_qty            NUMERIC(12)   NOT NULL,
    trade_price          NUMERIC(15,4) NOT NULL,
    trade_date           DATE          NOT NULL,
    created_at           TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_trade_account
      FOREIGN KEY (account_id) REFERENCES securities.account (account_id),
    CONSTRAINT fk_trade_product
      FOREIGN KEY (product_id) REFERENCES securities.product (product_id)
);

CREATE INDEX ix_trade_account_date ON securities.trade (account_id, trade_date);

COMMENT ON TABLE  securities.trade             IS '取引明細';
COMMENT ON COLUMN securities.trade.trade_type  IS '取引種別 B=買付 / S=売却';
COMMENT ON COLUMN securities.trade.trade_qty   IS '取引数量';
COMMENT ON COLUMN securities.trade.trade_price IS '約定単価';
